import type { Archetype, Module, Ticket, TicketType } from './types';

export const ARCHETYPES: Archetype[] = [
  {
    id: 'rockstar',
    name: 'The Rockstar',
    emoji: '🤘',
    skill: 9,
    baseEnergy: 70,
    ego: 9,
    quirk: { name: 'Language hopper', desc: 'Rewrites modules in a new language' },
    workMod: 1.4,
    bugChance: 0.05,
    quirkChance: 0.25,
  },
  {
    id: 'grindset',
    name: 'The Grindset',
    emoji: '⚡',
    skill: 6,
    baseEnergy: 95,
    ego: 5,
    quirk: { name: '14-hour days', desc: 'Pulls brutal hours, burns out fast' },
    workMod: 1.2,
    bugChance: 0.15,
    quirkChance: 0.2,
  },
  {
    id: 'architect',
    name: 'The Architect',
    emoji: '🏛️',
    skill: 8,
    baseEnergy: 60,
    ego: 8,
    quirk: { name: 'Service sprawl', desc: 'Adds a microservice to everything' },
    workMod: 1.0,
    bugChance: 0.08,
    quirkChance: 0.35,
  },
  {
    id: 'zen',
    name: 'The Zen Monk',
    emoji: '🧘',
    skill: 7,
    baseEnergy: 80,
    ego: 3,
    quirk: { name: 'Anti-urgency', desc: 'Refuses all urgency with a smile' },
    workMod: 0.9,
    bugChance: 0.05,
    quirkChance: 0.1,
  },
  {
    id: 'imposter',
    name: 'The Imposter',
    emoji: '😰',
    skill: 4,
    baseEnergy: 50,
    ego: 2,
    quirk: { name: 'Panic deletes', desc: 'Deletes code when stressed' },
    workMod: 0.8,
    bugChance: 0.25,
    quirkChance: 0.3,
  },
  {
    id: 'slackwiz',
    name: 'The Slack Wizard',
    emoji: '🪄',
    skill: 8,
    baseEnergy: 40,
    ego: 6,
    quirk: { name: 'Deadline magic', desc: 'Does 90% of work in the last hour' },
    workMod: 1.3,
    bugChance: 0.1,
    quirkChance: 0.2,
  },
  {
    id: 'framework',
    name: 'The Framework Chaser',
    emoji: '📦',
    skill: 6,
    baseEnergy: 70,
    ego: 7,
    quirk: { name: 'Stack migration', desc: 'Migrates the stack mid-sprint' },
    workMod: 1.0,
    bugChance: 0.18,
    quirkChance: 0.4,
  },
  {
    id: 'intern',
    name: 'The Intern',
    emoji: '🐣',
    skill: 2,
    baseEnergy: 85,
    ego: 1,
    quirk: { name: 'Eager but wrong', desc: 'Breaks staging, learns nothing, asks everything' },
    workMod: 0.5,
    bugChance: 0.3,
    quirkChance: 0.2,
  },
  {
    id: 'vendor',
    name: 'The Vendor',
    emoji: '💍',
    skill: 5,
    baseEnergy: 60,
    ego: 8,
    quirk: { name: 'Upsells everything', desc: 'Ships fast, invoices faster' },
    workMod: 0.7,
    bugChance: 0.1,
    quirkChance: 0.35,
  },
  {
    id: 'security',
    name: 'The Security Engineer',
    emoji: '🛡️',
    skill: 7,
    baseEnergy: 65,
    ego: 6,
    quirk: { name: 'Rubber-stamp denial', desc: 'Blocks deploys, hardens modules, helps nobody' },
    workMod: 0.6,
    bugChance: 0.02,
    quirkChance: 0.3,
  },
  {
    id: 'devrel',
    name: 'The DevRel',
    emoji: '🎤',
    skill: 3,
    baseEnergy: 75,
    ego: 7,
    quirk: { name: 'Conference circuit', desc: 'Ships nothing, brings in sponsorship money' },
    workMod: 0.3,
    bugChance: 0.05,
    quirkChance: 0.3,
  },
  {
    id: 'zealot',
    name: 'The Test Zealot',
    emoji: '🧪',
    skill: 7,
    baseEnergy: 65,
    ego: 6,
    quirk: { name: 'Test tunnel vision', desc: 'Only writes tests, no features' },
    workMod: 0.85,
    bugChance: 0.03,
    quirkChance: 0.25,
  },
];

export const ARCHETYPE_MAP: Record<string, Archetype> = Object.fromEntries(
  ARCHETYPES.map((a) => [a.id, a]),
);

export const NAMES = [
  'Priya', 'Marcus', 'Yuki', 'Derek', 'Sofia', 'Tunde', 'Alex', 'Nina',
  'Viktor', 'Hana', 'Omar', 'Jess', 'Chen', 'Ravi', 'Lena', 'Kofi',
];

export const MODULE_DEFS: Module[] = [
  { id: 'gateway', name: 'API Gateway', health: 80, debt: 20 },
  { id: 'auth', name: 'Auth Service', health: 75, debt: 25 },
  { id: 'payments', name: 'Payments', health: 70, debt: 35 },
  { id: 'pipeline', name: 'Data Pipeline', health: 65, debt: 40 },
  { id: 'mobile', name: 'Mobile App', health: 78, debt: 15 },
  { id: 'monolith', name: 'Legacy Monolith', health: 55, debt: 65 },
];

export const TICKET_TEMPLATES: Record<
  TicketType,
  { title: string; moduleId: string; effort: number }[]
> = {
  feature: [
    { title: 'Implement SSO', moduleId: 'auth', effort: 18 },
    { title: 'Dark mode toggle', moduleId: 'mobile', effort: 10 },
    { title: 'Usage-based billing', moduleId: 'payments', effort: 22 },
    { title: 'Push notifications', moduleId: 'mobile', effort: 14 },
    { title: 'AI-powered search', moduleId: 'gateway', effort: 25 },
    { title: 'CSV export', moduleId: 'pipeline', effort: 8 },
    { title: 'Two-factor auth via carrier pigeon', moduleId: 'auth', effort: 20 },
    { title: 'In-app meditation timer', moduleId: 'mobile', effort: 6 },
    { title: 'Refund automation with vibes', moduleId: 'payments', effort: 16 },
    { title: 'Easter egg: Konami code for free coffee', moduleId: 'gateway', effort: 5 },
    { title: 'Multi-language toast notifications', moduleId: 'mobile', effort: 12 },
    { title: 'OAuth2 with a QR code and a prayer', moduleId: 'auth', effort: 28 },
    { title: 'Real-time stock ticker for internal metrics', moduleId: 'gateway', effort: 20 },
    { title: 'Export to PDF (the PDF will be a lie)', moduleId: 'pipeline', effort: 10 },
    { title: 'Swipe gesture for delete confirmation', moduleId: 'mobile', effort: 8 },
    { title: 'Webhook to a dead man\'s switch', moduleId: 'gateway', effort: 15 },
    { title: 'Auto-resolve support tickets with AI', moduleId: 'pipeline', effort: 30 },
    { title: 'Biometric login via typing cadence', moduleId: 'auth', effort: 24 },
    { title: 'Dark mode for the dark mode', moduleId: 'mobile', effort: 4 },
    { title: 'Feature flag for the feature flag system', moduleId: 'gateway', effort: 18 },
  ],
  bug: [
    { title: 'NPE in checkout flow', moduleId: 'payments', effort: 10 },
    { title: 'Race condition in webhooks', moduleId: 'gateway', effort: 14 },
    { title: 'Memory leak in report job', moduleId: 'pipeline', effort: 12 },
    { title: 'CORS errors on staging', moduleId: 'gateway', effort: 7 },
    { title: 'Double charge in payments', moduleId: 'payments', effort: 15 },
    { title: 'Session expiry loop', moduleId: 'auth', effort: 9 },
    { title: 'Undefined is not a function (it is, you\'re just wrong)', moduleId: 'monolith', effort: 6 },
    { title: 'Staging looks different from production (shocker)', moduleId: 'gateway', effort: 8 },
    { title: 'Ghost user created by midnight cron job', moduleId: 'payments', effort: 11 },
    { title: 'Mobile app crashes when rotating device in air', moduleId: 'mobile', effort: 13 },
    { title: 'Rate limiter blocked the CEO\'s API calls', moduleId: 'gateway', effort: 5 },
    { title: 'Database migration dropped the users table (temporarily)', moduleId: 'monolith', effort: 20 },
    { title: 'Email sent to all users: "You have been selected"', moduleId: 'pipeline', effort: 9 },
    { title: 'Websocket connection stuck in eternal reconnect', moduleId: 'gateway', effort: 7 },
    { title: 'Cache returned yesterday\'s price for today\'s purchase', moduleId: 'payments', effort: 6 },
    { title: 'Auth service logged password in plaintext (oops)', moduleId: 'auth', effort: 18 },
    { title: 'Push notification sent to 10k devices at 3am', moduleId: 'mobile', effort: 4 },
    { title: 'Data pipeline duplicated last month\'s revenue', moduleId: 'pipeline', effort: 14 },
    { title: 'Search returned results from 2019 archive', moduleId: 'gateway', effort: 10 },
    { title: 'File upload accepted .exe files (security team is crying)', moduleId: 'monolith', effort: 8 },
  ],
  epic: [
    { title: 'Migrate to Kubernetes', moduleId: 'gateway', effort: 35 },
    { title: 'Multi-tenant refactor', moduleId: 'monolith', effort: 42 },
    { title: 'Replatform data warehouse', moduleId: 'pipeline', effort: 38 },
    { title: 'Replace monolith with serverless (serverless with monolith)', moduleId: 'monolith', effort: 50 },
    { title: 'Build internal design system (from Figma, not code)', moduleId: 'mobile', effort: 30 },
    { title: 'Implement event sourcing (for the event sourcing)', moduleId: 'gateway', effort: 45 },
    { title: 'GraphQL federation (each service has its own GraphQL)', moduleId: 'gateway', effort: 40 },
    { title: 'Zero-downtime deploy (requires zero downtime humans)', moduleId: 'pipeline', effort: 35 },
    { title: 'Auth rewrite: JWT + OAuth + magic links + carrier pigeon', moduleId: 'auth', effort: 48 },
    { title: 'Full observability stack (tracing, metrics, logs, tears)', moduleId: 'gateway', effort: 32 },
    { title: 'Micro-frontend architecture (each frontend is micro)', moduleId: 'mobile', effort: 38 },
    { title: 'Compliance audit prep (SOC2, ISO, HIPAA, vibes)', moduleId: 'monolith', effort: 28 },
  ],
};

export const TEAM_CHANNELS = ['#dev-team', '#random', '#incidents', '#announcements'];

export const TEAM_IDLE = [
  'anyone else seeing CI be weird or is it just me',
  'lunch? 🍜',
  'hot take: the roadmap is a vibe',
  'I have not touched the codebase since 2019 and I am FINE',
  'standup could have been a calendar invite',
  'who renamed the staging env again',
  'deploying on friday is a lifestyle',
  'my IDE just said something unkind about my code',
  'brb, my cat walked across the keyboard',
  'has anyone tried turning it off and on again?',
  'I\'m not procrastinating, I\'m doing deep thinking',
  'just discovered dark mode in VS Code. life changing.',
  'my git blame is a horror story',
  'if I could live in my terminal I would',
  'the code compiles! ...for now',
  'I\'ve been debugging for 3 hours. it was a typo.',
  'who approved this PR? ...oh wait, that was me',
  'deploying to prod on a Monday is just wellness',
  'my commit message game is strong',
  'I\'m not saying the code is messy, but the linter cried',
];

export const TEAM_ARGUMENTS = [
  'we need to talk about the architecture. again.',
  'this PR is a crime against humanity',
  'can we PLEASE stop debating naming conventions',
  'I will not be reviewing another 4k-line diff',
  'someone put a TODO in PRODUCTION',
  'the monolith is not "a strategic choice", it is a hostage',
  'if we just use a new language this solves everything',
  'I wrote this code and I don\'t recognize it anymore',
  'the tests pass but I can feel the lies',
  'why are we still using REST in 2024',
  'microservices are just monoliths with extra steps',
  'I asked for a code review, not a philosophy debate',
  'the CI pipeline takes longer than the sprint',
  'who set the timeout to 30 seconds? this is a war crime',
  'I\'ve seen cleaner code in a ransom note',
  'the documentation says it\'s supposed to do that',
  'I\'m not arguing, I\'m explaining why I\'m right',
  'this is why we can\'t have nice things',
  'I\'ll merge it, don\'t make me regret it',
  'the bug is a feature, you just don\'t get it',
];

export const TEAM_PANIC = [
  'STAGING IS DOWN. I repeat. STAGING IS DOWN.',
  'the pager is not a toy',
  'I am deleting my branch. everything is fine.',
  'why is prod talking to the sandbox db',
  'PROD IS ON FIRE AND THE FIRE ALARM IS THE TEAMS NOTIFICATION',
  'I just pushed a hotfix. it broke more things. standard procedure.',
  'the database is locked. by whom? by our poor life choices.',
  'I accidentally ran `rm -rf` on the wrong box. it was prod.',
  'the load balancer is load-balancing to nowhere',
  'someone just deployed on a Friday. I\'m calling HR.',
  'the SSL cert expired and I\'m pretty sure it\'s my fault',
  'the queue is backing up and I can hear the messages screaming',
  'I tried to scale up but the cloud bill screamed first',
  'the monitoring dashboard is just red now. we\'ve accepted it.',
  'the CDN is caching 404s. even our errors are broken.',
];

export interface GameEvent {
  name: string;
  weight: number;
  apply: (state: import('./types').GameState) => void;
}
