export const ARCHETYPES: Archetype[[
  {
    id: 'architect',
    name: 'The Architect',
    emoji: '🏛️',
    skill: 8,
    baseEnergy: 60,
    ego: 8,
    quirk: { name: 'Service sprawl', desc: 'Adds a microservice to everything' },
    workMod: 1.0,
    bugChance: 0.08,
    quirkChance: 0.35,
  },
  {
    id: 'devrel',
    name: 'The DevRel',
    emoji: '🎤',
    skill: 3,
    baseEnergy: 75,
    ego: 7,
    quirk: { name: 'Conference circuit', desc: 'Ships nothing, brings in sponsorship money' },
    workMod: 0.3,
    bugChance: 0.05,
    quirkChance: 0.3,
  },
  {
    id: 'framework',
    name: 'The Framework Chaser',
    emoji: '📦',
    skill: 6,
    baseEnergy: 70,
    ego: 7,
    quirk: { name: 'Stack migration', desc: 'Migrates the stack mid-sprint' },
    workMod: 1.0,
    bugChance: 0.18,
    quirkChance: 0.4,
  },
  {
    id: 'grindset',
    name: 'The Grindset',
    emoji: '⚡',
    skill: 6,
    baseEnergy: 95,
    ego: 5,
    quirk: { name: '14-hour days', desc: 'Pulls brutal hours, burns out fast' },
    workMod: 1.2,
    bugChance: 0.15,
    quirkChance: 0.2,
  },
  {
    id: 'imposter',
    name: 'The Imposter',
    emoji: '😰',
    skill: 4,
    baseEnergy: 50,
    ego: 2,
    quirk: { name: 'Panic deletes', desc: 'Deletes code when stressed' },
    workMod: 0.8,
    bugChance: 0.25,
    quirkChance: 0.3,
  },
  {
    id: 'intern',
    name: 'The Intern',
    emoji: '🐣',
    skill: 2,
    baseEnergy: 85,
    ego: 1,
    quirk: { name: 'Eager but wrong', desc: 'Breaks staging, learns nothing, asks everything' },
    workMod: 0.5,
    bugChance: 0.3,
    quirkChance: 0.2,
  },
  {
    id: 'rockstar',
    name: 'The Rockstar',
    emoji: '🤘',
    skill: 9,
    baseEnergy: 70,
    ego: 9,
    quirk: { name: 'Language hopper', desc: 'Rewrites modules in a new language' },
    workMod: 1.4,
    bugChance: 0.05,
    quirkChance: 0.25,
  },
  {
    id: 'security',
    name: 'The Security Engineer',
    emoji: '🛡️',
    skill: 7,
    baseEnergy: 65,
    ego: 6,
    quirk: { name: 'Rubber-stamp denial', desc: 'Blocks deploys, hardens modules, helps nobody' },
    workMod: 0.6,
    bugChance: 0.02,
    quirkChance: 0.3,
  },
  {
    id: 'slackwiz',
    name: 'The Slack Wizard',
    emoji: '🪄',
    skill: 8,
    baseEnergy: 40,
    ego: 6,
    quirk: { name: 'Deadline magic', desc: 'Does 90% of work in the last hour' },
    workMod: 1.3,
    bugChance: 0.1,
    quirkChance: 0.2,
  },
  {
    id: 'vendor',
    name: 'The Vendor',
    emoji: '💍',
    skill: 5,
    baseEnergy: 60,
    ego: 8,
    quirk: { name: 'Upsells everything', desc: 'Ships fast, invoices faster' },
    workMod: 0.7,
    bugChance: 0.1,
    quirkChance: 0.35,
  },
  {
    id: 'zealot',
    name: 'The Test Zealot',
    emoji: '🧪',
    skill: 7,
    baseEnergy: 65,
    ego: 6,
    quirk: { name: 'Test tunnel vision', desc: 'Only writes tests, no features' },
    workMod: 0.85,
    bugChance: 0.03,
    quirkChance: 0.25,
  },
  {
    id: 'zen',
    name: 'The Zen Monk',
    emoji: '🧘',
    skill: 7,
    baseEnergy: 80,
    ego: 3,
    quirk: { name: 'Anti-urgency', desc: 'Refuses all urgency with a smile' },
    workMod: 0.9,
    bugChance: 0.05,
    quirkChance: 0.1,
  },
  ]];